services:
  isla_file:
    build:
      context: ./Isla_File
      dockerfile: Dockerfile
    container_name: isla_file
    ports:
      - "50051:50051"
    networks:
      - test_network

  datanode1:
    build:
      context: ./datanode1
      dockerfile: Dockerfile
    container_name: datanode1
    ports:
      - "50054:50054"
    networks:
      - test_network

networks:
  test_network:
    external: true
